[package]
name = "wgpp-include"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.89" }
quote = "1.0.17"
proc-macro2 = "1.0.36"
naga = { version = "0.11", features = ["validate", "span", "wgsl-in"] }

wgpp = { path = "../wgpp" }